# ------ root_path/dataset_name ------
root_path: ''

# ------ Hyperparamters ------
search_hp: True
search_scale: [30, 100]
search_step: [200, 20]

init_beta:  10
init_alpha: 25

# ------ Basic Config ------
dataset: 'organ_text'
shots: 16
cache_path: 'data_text.json'
data_path: 'data.json'
