sam_ckpt_path: '/home/kappa7077/MaskSam/Backbone/sam_vit_b.pth'
tp_ckpt_path: '/home/kappa7077/MaskSam/Backbone/tp.pth'
settings:
  USE_TEXT_PROMPT: True
  USE_MASK_PROMPT: True
  USE_LORA: True

training:
  optimizer: 'adamw'
  lr: 1e-4
  batch_size: 75
  num_epochs: 100
  weight_decay: 1e-3
  criterions: ['dice','focal']
  criterion_weights: [0.001,0.9]
  train_convolution: False
  train_cache: True