data:
  name: Synapse
  classes: 8
  img_size: 512
  # ------ root_path/dataset_name ------
  root_path: '/work/chen0063/Synapse'
  label_path: 'slice_data'
  image_path: 'train_npz'

  # ------ Hyperparamters ------
  beta: 10
  alpha: 0.5
  # ------ Basic Config ------
  shots: 16
  cache_path: 'cache.json'
  data_path: 'data.json'
  Notalldata_path: 'data_notall_shuffle.json'
  data_type: 'nall'
  label_names: ['spleen','right kidney','left kidney','gallbladder','liver','stomach','aorta','pancreas']
  label_weight: [1.15,1.11,1.12,5,1,3,1.1,5]
